### ISSUE TITLE
AttributeError: module 'em' has no attribute 'RAW_OPT'

### ISSUE THREAD

**Issue by HuaYuXiao** [HuaYuXiao/uav_navigation#25]
```bash
hyx020222@ubuntu:~/prometheus_px4$ sudo make amovlab_sitl_default gazebo_p450
[sudo] password for hyx020222: 
[0/813] git submodule src/drivers/gps/devices
[1/813] git submodule src/lib/ecl
[2/813] Generating uORB topic headers
FAILED: uORB/topics/uORBTopics.hpp uORB/topics/actuator_armed.h uORB/topics/actuator_controls.h uORB/topics/actuator_outputs.h uORB/topics/adc_report.h uORB/topics/airspeed.h uORB/topics/airspeed_validated.h uORB/topics/airspeed_wind.h uORB/topics/battery_status.h uORB/topics/camera_capture.h uORB/topics/camera_trigger.h uORB/topics/cellular_status.h uORB/topics/collision_constraints.h uORB/topics/collision_report.h uORB/topics/commander_state.h uORB/topics/control_allocator_status.h uORB/topics/cpuload.h uORB/topics/debug_array.h uORB/topics/debug_key_value.h uORB/topics/debug_value.h uORB/topics/debug_vect.h uORB/topics/differential_pressure.h uORB/topics/distance_sensor.h uORB/topics/ekf2_timestamps.h uORB/topics/ekf_gps_drift.h uORB/topics/esc_report.h uORB/topics/esc_status.h uORB/topics/estimator_event_flags.h uORB/topics/estimator_innovations.h uORB/topics/estimator_optical_flow_vel.h uORB/topics/estimator_selector_status.h uORB/topics/estimator_sensor_bias.h uORB/topics/estimator_states.h uORB/topics/estimator_status.h uORB/topics/estimator_status_flags.h uORB/topics/follow_target.h uORB/topics/generator_status.h uORB/topics/geofence_result.h uORB/topics/gimbal_device_attitude_status.h uORB/topics/gimbal_device_information.h uORB/topics/gimbal_device_set_attitude.h uORB/topics/gimbal_manager_information.h uORB/topics/gimbal_manager_set_attitude.h uORB/topics/gimbal_manager_set_manual_control.h uORB/topics/gimbal_manager_status.h uORB/topics/gps_dump.h uORB/topics/gps_inject_data.h uORB/topics/heater_status.h uORB/topics/home_position.h uORB/topics/hover_thrust_estimate.h uORB/topics/input_rc.h uORB/topics/iridiumsbd_status.h uORB/topics/irlock_report.h uORB/topics/landing_gear.h uORB/topics/landing_target_innovations.h uORB/topics/landing_target_pose.h uORB/topics/led_control.h uORB/topics/log_message.h uORB/topics/logger_status.h uORB/topics/mag_worker_data.h uORB/topics/manual_control_setpoint.h uORB/topics/manual_control_switches.h uORB/topics/mavlink_log.h uORB/topics/mission.h uORB/topics/mission_result.h uORB/topics/mount_orientation.h uORB/topics/multirotor_motor_limits.h uORB/topics/navigator_mission_item.h uORB/topics/obstacle_distance.h uORB/topics/offboard_control_mode.h uORB/topics/onboard_computer_status.h uORB/topics/optical_flow.h uORB/topics/orb_test.h uORB/topics/orb_test_large.h uORB/topics/orb_test_medium.h uORB/topics/orbit_status.h uORB/topics/parameter_update.h uORB/topics/ping.h uORB/topics/position_controller_landing_status.h uORB/topics/position_controller_status.h uORB/topics/position_setpoint.h uORB/topics/position_setpoint_triplet.h uORB/topics/power_button_state.h uORB/topics/power_monitor.h uORB/topics/pwm_input.h uORB/topics/px4io_status.h uORB/topics/qshell_req.h uORB/topics/qshell_retval.h uORB/topics/radio_status.h uORB/topics/rate_ctrl_status.h uORB/topics/rc_channels.h uORB/topics/rc_parameter_map.h uORB/topics/rpm.h uORB/topics/rtl_flight_time.h uORB/topics/safety.h uORB/topics/satellite_info.h uORB/topics/sensor_accel.h uORB/topics/sensor_accel_fifo.h uORB/topics/sensor_baro.h uORB/topics/sensor_combined.h uORB/topics/sensor_correction.h uORB/topics/sensor_gps.h uORB/topics/sensor_gyro.h uORB/topics/sensor_gyro_fft.h uORB/topics/sensor_gyro_fifo.h uORB/topics/sensor_mag.h uORB/topics/sensor_preflight_mag.h uORB/topics/sensor_selection.h uORB/topics/sensors_status_imu.h uORB/topics/system_power.h uORB/topics/takeoff_status.h uORB/topics/task_stack_info.h uORB/topics/tecs_status.h uORB/topics/telemetry_status.h uORB/topics/test_motor.h uORB/topics/timesync.h uORB/topics/timesync_status.h uORB/topics/trajectory_bezier.h uORB/topics/trajectory_waypoint.h uORB/topics/transponder_report.h uORB/topics/tune_control.h uORB/topics/uavcan_parameter_request.h uORB/topics/uavcan_parameter_value.h uORB/topics/ulog_stream.h uORB/topics/ulog_stream_ack.h uORB/topics/vehicle_acceleration.h uORB/topics/vehicle_actuator_setpoint.h uORB/topics/vehicle_air_data.h uORB/topics/vehicle_angular_acceleration.h uORB/topics/vehicle_angular_acceleration_setpoint.h uORB/topics/vehicle_angular_velocity.h uORB/topics/vehicle_attitude.h uORB/topics/vehicle_attitude_setpoint.h uORB/topics/vehicle_command.h uORB/topics/vehicle_command_ack.h uORB/topics/vehicle_constraints.h uORB/topics/vehicle_control_mode.h uORB/topics/vehicle_global_position.h uORB/topics/vehicle_gps_position.h uORB/topics/vehicle_imu.h uORB/topics/vehicle_imu_status.h uORB/topics/vehicle_land_detected.h uORB/topics/vehicle_local_position.h uORB/topics/vehicle_local_position_setpoint.h uORB/topics/vehicle_magnetometer.h uORB/topics/vehicle_odometry.h uORB/topics/vehicle_rates_setpoint.h uORB/topics/vehicle_roi.h uORB/topics/vehicle_status.h uORB/topics/vehicle_status_flags.h uORB/topics/vehicle_thrust_setpoint.h uORB/topics/vehicle_torque_setpoint.h uORB/topics/vehicle_trajectory_bezier.h uORB/topics/vehicle_trajectory_waypoint.h uORB/topics/vtol_vehicle_status.h uORB/topics/wheel_encoders.h uORB/topics/wind.h uORB/topics/yaw_estimator_status.h 
cd /home/hyx020222/prometheus_px4/msg && /usr/bin/python3 tools/px_generate_uorb_topic_files.py --headers -f actuator_armed.msg actuator_controls.msg actuator_outputs.msg adc_report.msg airspeed.msg airspeed_validated.msg airspeed_wind.msg battery_status.msg camera_capture.msg camera_trigger.msg cellular_status.msg collision_constraints.msg collision_report.msg commander_state.msg control_allocator_status.msg cpuload.msg debug_array.msg debug_key_value.msg debug_value.msg debug_vect.msg differential_pressure.msg distance_sensor.msg ekf2_timestamps.msg ekf_gps_drift.msg esc_report.msg esc_status.msg estimator_event_flags.msg estimator_innovations.msg estimator_optical_flow_vel.msg estimator_selector_status.msg estimator_sensor_bias.msg estimator_states.msg estimator_status.msg estimator_status_flags.msg follow_target.msg generator_status.msg geofence_result.msg gimbal_device_attitude_status.msg gimbal_device_information.msg gimbal_device_set_attitude.msg gimbal_manager_information.msg gimbal_manager_set_attitude.msg gimbal_manager_set_manual_control.msg gimbal_manager_status.msg gps_dump.msg gps_inject_data.msg heater_status.msg home_position.msg hover_thrust_estimate.msg input_rc.msg iridiumsbd_status.msg irlock_report.msg landing_gear.msg landing_target_innovations.msg landing_target_pose.msg led_control.msg log_message.msg logger_status.msg mag_worker_data.msg manual_control_setpoint.msg manual_control_switches.msg mavlink_log.msg mission.msg mission_result.msg mount_orientation.msg multirotor_motor_limits.msg navigator_mission_item.msg obstacle_distance.msg offboard_control_mode.msg onboard_computer_status.msg optical_flow.msg orb_test.msg orb_test_large.msg orb_test_medium.msg orbit_status.msg parameter_update.msg ping.msg position_controller_landing_status.msg position_controller_status.msg position_setpoint.msg position_setpoint_triplet.msg power_button_state.msg power_monitor.msg pwm_input.msg px4io_status.msg qshell_req.msg qshell_retval.msg radio_status.msg rate_ctrl_status.msg rc_channels.msg rc_parameter_map.msg rpm.msg rtl_flight_time.msg safety.msg satellite_info.msg sensor_accel.msg sensor_accel_fifo.msg sensor_baro.msg sensor_combined.msg sensor_correction.msg sensor_gps.msg sensor_gyro.msg sensor_gyro_fft.msg sensor_gyro_fifo.msg sensor_mag.msg sensor_preflight_mag.msg sensor_selection.msg sensors_status_imu.msg system_power.msg takeoff_status.msg task_stack_info.msg tecs_status.msg telemetry_status.msg test_motor.msg timesync.msg timesync_status.msg trajectory_bezier.msg trajectory_waypoint.msg transponder_report.msg tune_control.msg uavcan_parameter_request.msg uavcan_parameter_value.msg ulog_stream.msg ulog_stream_ack.msg vehicle_acceleration.msg vehicle_actuator_setpoint.msg vehicle_air_data.msg vehicle_angular_acceleration.msg vehicle_angular_acceleration_setpoint.msg vehicle_angular_velocity.msg vehicle_attitude.msg vehicle_attitude_setpoint.msg vehicle_command.msg vehicle_command_ack.msg vehicle_constraints.msg vehicle_control_mode.msg vehicle_global_position.msg vehicle_gps_position.msg vehicle_imu.msg vehicle_imu_status.msg vehicle_land_detected.msg vehicle_local_position.msg vehicle_local_position_setpoint.msg vehicle_magnetometer.msg vehicle_odometry.msg vehicle_rates_setpoint.msg vehicle_roi.msg vehicle_status.msg vehicle_status_flags.msg vehicle_thrust_setpoint.msg vehicle_torque_setpoint.msg vehicle_trajectory_bezier.msg vehicle_trajectory_waypoint.msg vtol_vehicle_status.msg wheel_encoders.msg wind.msg yaw_estimator_status.msg -i /home/hyx020222/prometheus_px4/msg -o /home/hyx020222/prometheus_px4/build/amovlab_sitl_default/uORB/topics -e templates/uorb -t /home/hyx020222/prometheus_px4/build/amovlab_sitl_default/msg/tmp/headers -q
Traceback (most recent call last):
  File "tools/px_generate_uorb_topic_files.py", line 530, in <module>
    generate_idx, f, args.temporarydir, args.package, args.templatedir, INCL_DEFAULT)
  File "tools/px_generate_uorb_topic_files.py", line 177, in generate_output_from_file
    return generate_by_template(output_file, template_file, em_globals)
  File "tools/px_generate_uorb_topic_files.py", line 346, in generate_by_template
    em.RAW_OPT: True, em.BUFFERED_OPT: True})
AttributeError: module 'em' has no attribute 'RAW_OPT'
[3/813] Building CXX object boards/amovlab/sitl/src/CMakeFiles/drivers_board.dir/board_shutdown.cpp.o
ninja: build stopped: subcommand failed.
Makefile:224: recipe for target 'amovlab_sitl_default' failed
make: *** [amovlab_sitl_default] Error 1
```

**Comment by HuaYuXiao** [comment]
```bash
pip3 uninstall empy
```

```bash
pip3 install empy==3.3.4
```

Reference:
- https://stackoverflow.com/questions/77642155/attributeerror-module-object-has-no-attribute-raw-opt/77656642#77656642
